# The name must match serviceAccount.name in helm/snmp-exporter.yaml.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: snmp-exporter
  namespace: snmp-exporter
  labels:
    app.kubernetes.io/name: prometheus-snmp-exporter
    app.kubernetes.io/instance: snmp-exporter
    app.kubernetes.io/version: "v0.30.1"
automountServiceAccountToken: false
