# The name must match serviceAccount.name in helm/smartctl-exporter.yaml.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: smartctl-exporter
  labels:
    app.kubernetes.io/name: prometheus-smartctl-exporter
    app.kubernetes.io/instance: smartctl-exporter
    app.kubernetes.io/version: "v0.14.0"
automountServiceAccountToken: false
